name: HW3_CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  main-work:
    runs-on: spartan-4

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: garygrossgarten/github-action-ssh@release
        with:
          host: 10.10.10.113
          username: hoplite
          password: 123
          command: |
            bash check-submission.sh all
